//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBIS.NG.Adapter.HUAUPC
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types", ConfigurationName="UBIS.NG.Adapter.HUAUPC.SPCPort")]
    public interface SPCPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        System.Threading.Tasks.Task<UBIS.NG.Adapter.HUAUPC.InitiateStorageResponse1> InitiateStorageAsync(UBIS.NG.Adapter.HUAUPC.InitiateStorageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        System.Threading.Tasks.Task<UBIS.NG.Adapter.HUAUPC.UploadFileResponse1> UploadFileAsync(UBIS.NG.Adapter.HUAUPC.UploadFileRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        System.Threading.Tasks.Task<UBIS.NG.Adapter.HUAUPC.DeleteFileResponse1> DeleteFileAsync(UBIS.NG.Adapter.HUAUPC.DeleteFileRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        System.Threading.Tasks.Task<UBIS.NG.Adapter.HUAUPC.GetStatusResponse1> GetStatusAsync(UBIS.NG.Adapter.HUAUPC.GetStatusRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types")]
    public partial class UploadItem
    {
        
        private string workingFolderField;
        
        private Document originalDocumentField;
        
        private Document[] childDocumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string workingFolder
        {
            get
            {
                return this.workingFolderField;
            }
            set
            {
                this.workingFolderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Document originalDocument
        {
            get
            {
                return this.originalDocumentField;
            }
            set
            {
                this.originalDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("childDocument", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Document[] childDocument
        {
            get
            {
                return this.childDocumentField;
            }
            set
            {
                this.childDocumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types")]
    public partial class Document
    {
        
        private string fileIdField;
        
        private string docIdField;
        
        private string versionSeriesIdField;
        
        private bool alreadyStoredField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileId
        {
            get
            {
                return this.fileIdField;
            }
            set
            {
                this.fileIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string docId
        {
            get
            {
                return this.docIdField;
            }
            set
            {
                this.docIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string versionSeriesId
        {
            get
            {
                return this.versionSeriesIdField;
            }
            set
            {
                this.versionSeriesIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool alreadyStored
        {
            get
            {
                return this.alreadyStoredField;
            }
            set
            {
                this.alreadyStoredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types")]
    public partial class FileInformation
    {
        
        private string fileIdField;
        
        private string statusField;
        
        private string versionSeriesIdField;
        
        private int reasonCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileId
        {
            get
            {
                return this.fileIdField;
            }
            set
            {
                this.fileIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string versionSeriesId
        {
            get
            {
                return this.versionSeriesIdField;
            }
            set
            {
                this.versionSeriesIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int reasonCode
        {
            get
            {
                return this.reasonCodeField;
            }
            set
            {
                this.reasonCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types")]
    public partial class UploadItemResponse
    {
        
        private string fileIdField;
        
        private int codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileId
        {
            get
            {
                return this.fileIdField;
            }
            set
            {
                this.fileIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types")]
    public partial class BaseResponse
    {
        
        private int codeField;
        
        private string errorTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorText
        {
            get
            {
                return this.errorTextField;
            }
            set
            {
                this.errorTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types")]
    public partial class InitiateStorageResponse : BaseResponse
    {
        
        private UploadItemResponse[] uploadItemResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uploadItemResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UploadItemResponse[] uploadItemResponse
        {
            get
            {
                return this.uploadItemResponseField;
            }
            set
            {
                this.uploadItemResponseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InitiateStorageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InitiateStorageRequest", Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("uploadItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UBIS.NG.Adapter.HUAUPC.UploadItem[] InitiateStorageRequest1;
        
        public InitiateStorageRequest()
        {
        }
        
        public InitiateStorageRequest(UBIS.NG.Adapter.HUAUPC.UploadItem[] InitiateStorageRequest1)
        {
            this.InitiateStorageRequest1 = InitiateStorageRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InitiateStorageResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types", Order=0)]
        public UBIS.NG.Adapter.HUAUPC.InitiateStorageResponse InitiateStorageResponse;
        
        public InitiateStorageResponse1()
        {
        }
        
        public InitiateStorageResponse1(UBIS.NG.Adapter.HUAUPC.InitiateStorageResponse InitiateStorageResponse)
        {
            this.InitiateStorageResponse = InitiateStorageResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types")]
    public partial class UploadFileRequest
    {
        
        private string workingFolderField;
        
        private string fileIdField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string workingFolder
        {
            get
            {
                return this.workingFolderField;
            }
            set
            {
                this.workingFolderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileId
        {
            get
            {
                return this.fileIdField;
            }
            set
            {
                this.fileIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types")]
    public partial class UploadFileResponse : BaseResponse
    {
        
        private FileInformation[] fileInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FileInformation[] fileInfo
        {
            get
            {
                return this.fileInfoField;
            }
            set
            {
                this.fileInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types", Order=0)]
        public UBIS.NG.Adapter.HUAUPC.UploadFileRequest UploadFileRequest;
        
        public UploadFileRequest1()
        {
        }
        
        public UploadFileRequest1(UBIS.NG.Adapter.HUAUPC.UploadFileRequest UploadFileRequest)
        {
            this.UploadFileRequest = UploadFileRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types", Order=0)]
        public UBIS.NG.Adapter.HUAUPC.UploadFileResponse UploadFileResponse;
        
        public UploadFileResponse1()
        {
        }
        
        public UploadFileResponse1(UBIS.NG.Adapter.HUAUPC.UploadFileResponse UploadFileResponse)
        {
            this.UploadFileResponse = UploadFileResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types")]
    public partial class DeleteFileRequest
    {
        
        private string workingFolderField;
        
        private string fileIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string workingFolder
        {
            get
            {
                return this.workingFolderField;
            }
            set
            {
                this.workingFolderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileId
        {
            get
            {
                return this.fileIdField;
            }
            set
            {
                this.fileIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types")]
    public partial class DeleteFileResponse : BaseResponse
    {
        
        private FileInformation[] fileInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FileInformation[] fileInfo
        {
            get
            {
                return this.fileInfoField;
            }
            set
            {
                this.fileInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types", Order=0)]
        public UBIS.NG.Adapter.HUAUPC.DeleteFileRequest DeleteFileRequest;
        
        public DeleteFileRequest1()
        {
        }
        
        public DeleteFileRequest1(UBIS.NG.Adapter.HUAUPC.DeleteFileRequest DeleteFileRequest)
        {
            this.DeleteFileRequest = DeleteFileRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types", Order=0)]
        public UBIS.NG.Adapter.HUAUPC.DeleteFileResponse DeleteFileResponse;
        
        public DeleteFileResponse1()
        {
        }
        
        public DeleteFileResponse1(UBIS.NG.Adapter.HUAUPC.DeleteFileResponse DeleteFileResponse)
        {
            this.DeleteFileResponse = DeleteFileResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types")]
    public partial class GetStatusResponse : BaseResponse
    {
        
        private FileInformation[] fileInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FileInformation[] fileInfo
        {
            get
            {
                return this.fileInfoField;
            }
            set
            {
                this.fileInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusRequest", Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("fileId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] GetStatusRequest1;
        
        public GetStatusRequest()
        {
        }
        
        public GetStatusRequest(string[] GetStatusRequest1)
        {
            this.GetStatusRequest1 = GetStatusRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.contum.hu/ypsilon/unicredit/aupc-ws-types", Order=0)]
        public UBIS.NG.Adapter.HUAUPC.GetStatusResponse GetStatusResponse;
        
        public GetStatusResponse1()
        {
        }
        
        public GetStatusResponse1(UBIS.NG.Adapter.HUAUPC.GetStatusResponse GetStatusResponse)
        {
            this.GetStatusResponse = GetStatusResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface SPCPortChannel : UBIS.NG.Adapter.HUAUPC.SPCPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class SPCPortClient : System.ServiceModel.ClientBase<UBIS.NG.Adapter.HUAUPC.SPCPort>, UBIS.NG.Adapter.HUAUPC.SPCPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SPCPortClient() : 
                base(SPCPortClient.GetDefaultBinding(), SPCPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SPCPortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SPCPortClient(EndpointConfiguration endpointConfiguration) : 
                base(SPCPortClient.GetBindingForEndpoint(endpointConfiguration), SPCPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SPCPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SPCPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SPCPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SPCPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SPCPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UBIS.NG.Adapter.HUAUPC.InitiateStorageResponse1> UBIS.NG.Adapter.HUAUPC.SPCPort.InitiateStorageAsync(UBIS.NG.Adapter.HUAUPC.InitiateStorageRequest request)
        {
            return base.Channel.InitiateStorageAsync(request);
        }
        
        public System.Threading.Tasks.Task<UBIS.NG.Adapter.HUAUPC.InitiateStorageResponse1> InitiateStorageAsync(UBIS.NG.Adapter.HUAUPC.UploadItem[] InitiateStorageRequest1)
        {
            UBIS.NG.Adapter.HUAUPC.InitiateStorageRequest inValue = new UBIS.NG.Adapter.HUAUPC.InitiateStorageRequest();
            inValue.InitiateStorageRequest1 = InitiateStorageRequest1;
            return ((UBIS.NG.Adapter.HUAUPC.SPCPort)(this)).InitiateStorageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UBIS.NG.Adapter.HUAUPC.UploadFileResponse1> UBIS.NG.Adapter.HUAUPC.SPCPort.UploadFileAsync(UBIS.NG.Adapter.HUAUPC.UploadFileRequest1 request)
        {
            return base.Channel.UploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<UBIS.NG.Adapter.HUAUPC.UploadFileResponse1> UploadFileAsync(UBIS.NG.Adapter.HUAUPC.UploadFileRequest UploadFileRequest)
        {
            UBIS.NG.Adapter.HUAUPC.UploadFileRequest1 inValue = new UBIS.NG.Adapter.HUAUPC.UploadFileRequest1();
            inValue.UploadFileRequest = UploadFileRequest;
            return ((UBIS.NG.Adapter.HUAUPC.SPCPort)(this)).UploadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UBIS.NG.Adapter.HUAUPC.DeleteFileResponse1> UBIS.NG.Adapter.HUAUPC.SPCPort.DeleteFileAsync(UBIS.NG.Adapter.HUAUPC.DeleteFileRequest1 request)
        {
            return base.Channel.DeleteFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<UBIS.NG.Adapter.HUAUPC.DeleteFileResponse1> DeleteFileAsync(UBIS.NG.Adapter.HUAUPC.DeleteFileRequest DeleteFileRequest)
        {
            UBIS.NG.Adapter.HUAUPC.DeleteFileRequest1 inValue = new UBIS.NG.Adapter.HUAUPC.DeleteFileRequest1();
            inValue.DeleteFileRequest = DeleteFileRequest;
            return ((UBIS.NG.Adapter.HUAUPC.SPCPort)(this)).DeleteFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UBIS.NG.Adapter.HUAUPC.GetStatusResponse1> UBIS.NG.Adapter.HUAUPC.SPCPort.GetStatusAsync(UBIS.NG.Adapter.HUAUPC.GetStatusRequest request)
        {
            return base.Channel.GetStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<UBIS.NG.Adapter.HUAUPC.GetStatusResponse1> GetStatusAsync(string[] GetStatusRequest1)
        {
            UBIS.NG.Adapter.HUAUPC.GetStatusRequest inValue = new UBIS.NG.Adapter.HUAUPC.GetStatusRequest();
            inValue.GetStatusRequest1 = GetStatusRequest1;
            return ((UBIS.NG.Adapter.HUAUPC.SPCPort)(this)).GetStatusAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SPCPortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SPCPortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://huhoaqlb.sd01.unicreditgroup.eu/aupc/ws");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SPCPortClient.GetBindingForEndpoint(EndpointConfiguration.SPCPortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SPCPortClient.GetEndpointAddress(EndpointConfiguration.SPCPortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            SPCPortSoap11,
        }
    }
}
